import type { Metadata } from "next";
import { Ubuntu_Sans } from "next/font/google";
import "./globals.css";

const ubuntuSans = Ubuntu_Sans({
  subsets: ["latin", "greek"], // "greek" subset is required — without it, Greek characters won't load correctly
  weight: ["400", "500", "600", "700"],
  variable: "--font-ubuntu-sans",
});

export const metadata: Metadata = {
  title: "PloumakisAgency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="el" className={`${ubuntuSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
