// Regenerates app/components/imageBlur.ts — a map of public image path to a
// base64 blur placeholder, so <Image placeholder="blur"> has something to show
// while the real photo is being optimized on demand.
//
// Next generates these automatically for statically imported images, but our
// product photos are referenced by path strings coming out of the CMS, so the
// map has to be built ahead of time and committed.
//
// Run it after adding or replacing anything in public/products/:
//   node scripts/generate-blur.mjs
//
// Uses macOS `sips`, so it is a local dev utility rather than a build step —
// the generated file is committed and CI never needs to run this.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const SOURCE_DIR = "public/products";
const OUT_FILE = "app/components/imageBlur.ts";
// 16px wide is enough to read as a colour wash once CSS scales it back up,
// and keeps each data URI small enough that inlining them all stays cheap.
const BLUR_WIDTH = 16;

const work = mkdtempSync(join(tmpdir(), "blur-"));

try {
  const files = readdirSync(SOURCE_DIR)
    .filter((name) => /\.(jpe?g|png)$/i.test(name))
    .sort();

  const entries = files.map((name) => {
    const out = join(work, name.replace(/\.[^.]+$/, ".jpg"));
    execFileSync("sips", [
      "--resampleWidth", String(BLUR_WIDTH),
      "-s", "format", "jpeg",
      "-s", "formatOptions", "60",
      join(SOURCE_DIR, name),
      "--out", out,
    ], { stdio: "ignore" });

    const base64 = readFileSync(out).toString("base64");
    return [`/products/${name}`, `data:image/jpeg;base64,${base64}`];
  });

  const body = entries
    .map(([path, uri]) => `  ${JSON.stringify(path)}: ${JSON.stringify(uri)},`)
    .join("\n");

  writeFileSync(
    OUT_FILE,
    `// GENERATED by scripts/generate-blur.mjs — do not edit by hand.\n` +
      `// Base64 blur placeholders for the product photos, keyed by public path.\n\n` +
      `export const BLUR_MAP: Record<string, string> = {\n${body}\n};\n`
  );

  console.log(`Wrote ${entries.length} placeholders to ${OUT_FILE}`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
